"""initial migrate

Revision ID: 2752a3636feb
Revises: 
Create Date: 2022-07-15 16:53:30.218106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2752a3636feb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sold')
    op.drop_table('users')
    op.drop_table('sits')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sits',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('avg_bill', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('total_kwh', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('new_price_with', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('new_price_without', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('offset', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('panels', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='sits_pkey')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key'),
    sa.UniqueConstraint('name', name='users_name_key')
    )
    op.create_table('sold',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('avg_bill', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('total_kwh', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('new_price_with', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('new_price_without', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('offset', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('panels', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('loan_provider', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('interest_rate', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('date_sold', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='sold_pkey')
    )
    # ### end Alembic commands ###
